version: '3'
services:
  # Jenkins master/UI running Blue Ocean
  # TODO: Pre-load all plugins
  jenkins-master:
    image: psc/jenkins:latest
    ports:
      - 8080:8080
    volumes:
      - jenkins_home:/var/jenkins_home

  # Sonarqube server for code metrics
  # TODO: Pre-load Find Security Bugs plugin
  # TODO: Change default credentials
  sonarqube:
    image: sonarqube:latest
    ports:
      - 9000:9000
      - 9092:9092
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
  
volumes:
  jenkins_home:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
